### ISSUE TITLE
보안 문제

### ISSUE THREAD

**Issue by level120** [devGW/video_repository#1]
# Readme.md 내용

```
동아리원들끼리 강좌를 조금 더 편하게 보기 위해 사이트 구축
저작권 문제가 될 수 있기 때문에 승인된 사용자만 열람 가능 
```

# 하지만?

![err](https://user-images.githubusercontent.com/10791961/56209306-25f5d080-608e-11e9-9c93-fd8a3d5bfd1b.png)

**Comment by level120** [comment]
추가적으로 가입승인 없이 업로드가 가능한 점이 제일 위험한 기능으로써 다시 검토하는 것을 요청함

**Comment by devGW** [comment]
문제점 수정완료. 피드백 감사합니다 ^^

**Comment by zi-gae** [comment]
> 추가적으로 가입승인 없이 업로드가 가능한 점이 제일 위험한 기능으로써 다시 검토하는 것을 요청함

문제점 수정완료. 피드백 감사합니다 ^^
